version: '3'

services:
  whatsapp-http-api:
    image: devlikeapro/whatsapp-http-api
    ports:
      - "3002:3000/tcp"
    stdin_open: true
    tty: true
    container_name: whatsapp-http
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 100M
        reservations:
          cpus: "1.0"
          memory: 10M